### ISSUE TITLE
Instructions are incorrect currently

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm_ppa_automation#6]
- key file is .asc, needs to be [kanidm_ppa.asc](https://raw.githubusercontent.com/kanidm/kanidm_ppa/refs/heads/main/kanidm_ppa.asc)
- apt list filter's wrong
- probably should call out that that nightly's are there and comment them out by default so monkeys like me don't automatically install them 🤦🏻 

## apt filter things 

```shell
sudo curl -s --compressed "https://kanidm.github.io/kanidm_ppa/kanidm_ppa.list" \
    | grep $( ( . /etc/os-release && echo $ID) ) \
    | sudo tee /etc/apt/sources.list.d/kanidm_ppa.list
```

ID probably needs to be VERSION_CODENAME?

```shell
sudo curl -s --compressed "https://kanidm.github.io/kanidm_ppa/kanidm_ppa.list" \
    | grep $( ( . /etc/os-release && echo $VERSION_CODENAME) ) \
    | sudo tee /etc/apt/sources.list.d/kanidm_ppa.list
```

debian:

```shell
# cat /etc/os-release
VERSION_CODENAME=bookworm
ID=debian
```

ubuntu:

```shell
# cat /etc/os-release
VERSION_CODENAME=noble
ID=ubuntu
```

**Comment by jinnatar** [comment]
The latest version of the instructions filters on `$VERSION_CODENAME`, but needs a rebuild to show up in the repo. In theory just re-triggering the previous run will fix this now that the upstream PR was merged.

**Comment by jinnatar** [comment]
I've re-triggered just the publish stage, that should update to the latest README.md: https://github.com/kanidm/kanidm_ppa_automation/actions/runs/11379035668

Confirmed, latest instructions now at: https://kanidm.github.io/kanidm_ppa/

Does that solve your issue?

**Comment by yaleman** [comment]
No worries at all, just had one of those "I'll quickly test thi.... oh no" mornings 😄 thanks for being super responsive as always!
